# Generated by Django 5.0.3 on 2024-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
